Update backend-ci.yml

diff --git a/.github/workflows/backend-ci.yml b/.github/workflows/backend-ci.yml
--- a/.github/workflows/backend-ci.yml
+++ b/.github/workflows/backend-ci.yml
@@ -27,9 +27,11 @@ jobs:
         run: ls ${{ github.workspace }}/back
       - name: search jacoco report
         run: ls ${{ github.workspace }}/back/target/site/jacoco
-      - name: Get test report
-        uses: actions/upload-artifact@v2  # upload test results
-        if: success() || failure()        # run this step even if previous step failed
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v12
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          name: jacoco-result
-          path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
+          name: JUNIT Tests            # Name of the check run which will be created
+          path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
